I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/episode1.rpy", line 85, in script
    init python:
  File "game/episode1.rpy", line 86, in <module>
    main_player.change_stats("Charisma", 1)
NameError: name 'main_player' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/episode1.rpy", line 85, in script
    init python:
  File "C:\Users\tusha\Downloads\Programs\Renpy\renpy-8.1.1-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\tusha\Downloads\Programs\Renpy\renpy-8.1.1-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/episode1.rpy", line 86, in <module>
    main_player.change_stats("Charisma", 1)
NameError: name 'main_player' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
day1 1.0
Tue Apr  9 03:12:31 2024
